"""empty message

Revision ID: 071d1d5c36eb
Revises: 16571dfa144f
Create Date: 2022-02-12 19:43:10.965926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071d1d5c36eb'
down_revision = '16571dfa144f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userType', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('isActive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isActive')
    op.drop_column('user', 'userType')
    # ### end Alembic commands ###
