"""empty message

Revision ID: 7d16ef780b0d
Revises: 071d1d5c36eb
Create Date: 2022-02-13 00:48:02.068938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d16ef780b0d'
down_revision = '071d1d5c36eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_userid_fkey', 'orders', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('orders_userid_fkey', 'orders', 'user', ['userid'], ['id'])
    # ### end Alembic commands ###
